# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: linux-ppc64le

env:
  matrix:
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "AtifPFbeNV5JD5cMUsDHNjsjLR1DySAqAx+GNOUqAQX5vVewPNypLkLk5QqfknFjno0dBAYbCCHYrgnroGEdHHwDu2j5tif45DduD1jjx5kihFldDQpV4f27lVDIyhoN6z09drqGdj8CWq6oJCr2bjh4Em5ZKOlZUK/s+9+GG7Rzu5WJfwqZ7f+dD6OiyGu+tyA5elW/NXLFMaKKuBvARxUauIu28O0RMv/FopQvzx0hv8HG1dKce+N8mRhUB0eLdvRUaTzDqiBxJldjFhn5hEB8IAwVe8gsUzANMW+VOvjSjShIsrMjg8bAiTA7loC3QQN+kbSnbnI+0bGfjrIgiDzuO7fyNsTmeyKOc69ya1XmLNq0aFo++18hX5gHw9Zha34sqMHsfXVE92Y51Inq/IUwqE+PL9NZD0jggIHAuGdV08DBmQyWBh38z4AqfRHKwByFN8kJOMlS2TogsfHxcFFlnUzQmBIiIKmY0B3DimWs9zrIgFYz3g5iZpivRBTw4LQ5RabRmNdDnbdoNKGcaOKfRFZmOdsn+ZWiavCfjxTSlMo6itTER8xybVtdZv5YbpVM650aNGTmR1bnE7lsZRdG1/QRCfnwEVywCRxB2SUg2xffG1yZJY77wD6vh7BlclVf26nehZXl0+28U8DSLvCJc539EceMLMNF5VJOmvM="
    
before_install:
    # Fast finish the PR.
    - sudo apt-get -qq update
    - sudo apt-get install  lftp
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-Linux-ppc64le.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b -bfp /opt/conda

    # Configure conda.
    - |
      echo "Configuring conda."
      source /opt/conda/bin/activate root
      conda install -y conda-build
      conda install -y anaconda-client
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda config --set anaconda_upload no
      #conda install --yes --quiet conda-forge-ci-setup=1
      #source run_conda_forge_build_setup

script:
  - conda build ./recipe
  - lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; set ssl-allow yes; set passive-mode yes; set ssl:verify-certificate no; put -O $FTP_DIRECTORY/linux-ppc64le $(ls /opt/conda/conda-bld/linux-ppc64le/keras-2.1.6-py*); cd power-ai; cd linux-ppc64le; chmod 777 $(cd /opt/conda/conda-bld/linux-ppc64le && ls keras-2.1.6-py*)  "
  #- upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
